### PR TITLE
adding failing tests --23 != 23

### PR DESCRIPTION
**Pull request by jasikpark**
do what you want with it?

the parsing of repeated plus or neg is not parsing correctly

### CODE REVIEW

**Comment by Lokathor** [comment]
Yeah, I guess it should accept `++54` as `54` for sure.

Having `--23`... hmm. I'm not sure if it should count as `-0-23` or more like `-(-23)`. Probably the latter

**Comment by jasikpark** [comment]
so... there's apparently a rust crate called [meval](https://github.com/rekka/meval-rs) that seems pretty great - I added it and a bunch more tests. Idk if you want to try to do your own thing or if [meval](https://github.com/rekka/meval-rs) sounds like a good idea to you.

**Comment by Lokathor** [comment]
Yeah, that looks good. Still have to be very picky for some types of parsing (`3d6*3d6` obviously shouldn't parse as `3d18d6`), but a guess we can allow a whole lot of math in other cases.

I'll try to get to these when I have a chance to sit down with it

**Comment by jasikpark** [comment]
yeah, that was the only thing about using `meval` - it'll parse *any* math we throw at it, rather than just the stuff we want.

**Comment by Lokathor** [comment]
My current first _guess_ is to use regex to find any XdY, pull it out and roll that, then replace that text with the result, and then keep going until there's no XdY left, and then meval that.

Which might even allow goofy things like `3d6d6` to parse (`3d6` rolls then that many `d6` is rolled, for some wildly varying number)

**Comment by jasikpark** [comment]
I mean what would probably actually be best is dropping `meval` since there's a lot of unneeded behavior that can't be disabled, and using [nom](https://github.com/Geal/nom) or [pest](https://pest.rs) - a parsing engine that can make all of this easier.

**Comment by jasikpark** [comment]
actually [pest](https://pest.rs) seems great since it has a calculator as a hello world example in the book for it, and there could definitely be a case where it can recognize "ndm" and roll for that.

**Comment by jasikpark** [comment]
or just leave it as is, and don't worry too much about it

**Pull request closed without merging**
